# Netlify Configuration File

# Redireciona todas as requisições que não correspondem a um arquivo
# existente para o index.html. Isso é essencial para Single Page Applications (SPAs).
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redireciona as requisições da sua API para o backend na EC2.
# Isso funciona como um proxy, permitindo que o frontend use um caminho
# relativo (ex: /api/auth) sem se preocupar com problemas de CORS.
[[redirects]]
  from = "/api/*"
  to = "https://54.90.176.166:5000/:splat"
  status = 200